name: Actor
main: com.insofar.actor.ActorPlugin
version: 0.1
description: >
             Actor Plugin by Joshua Weinberg
commands:
   record:
      description: start recording into buffer
      usage: /record
      
   stoprec:
      description: Stop recording
      usage: /stoprec
      
   actor:
      description: Spawn new actor using recording in buffer
      usage: /actor name
      
   dub:
      description: Duplicate one or all actors with a translation
      usage: /dub [name|all] x y z
      
   remove:
      description: Remove an actor(s). Name can be "all".
      usage: /remove name
      
   action:
      description: playback actor or all actors
      usage: /action [actorname]
      
   actionrec:
      description: playback actor or all actors and record
      usage: /actionrec [actorname]
      
   cut:
      description: Stop actor or all actors
      usage: /cut [actorname]

   reset:
      description: Rewind actor or all actors
      usage: /reset [actorname]
      
   remove:
      description: Remove an actor
      usage: /remove [actorname]
      
   saveactor:
      description: Save an actor's recording to a file
      usage: /save actorname filename
      
   savescene:
      description: Save all actor recordings to dir/actorname
      usage: /savescene scenename
      
   loadactor:
      description: Spawn an actor with the give recording file
      usage: /load actorname filename
      
   loadscene:
      description: Load and spawn all actor recordings from dir
      usage: /loadscene scenename
      
