name: Actor
main: com.insofar.actor.ActorPlugin
version: 0.41
description: >
             Actor Plugin by Joshua Weinberg
commands:
   record:
      description: start recording into buffer
      usage: /record
      
   cut:
      description: Stop recording and playback on all actors
      usage: /cut

   actor:
      description: Spawn new actor using recording in buffer
      usage: /actor name
      
   dub:
      description: Duplicate one or all actors with a translation
      usage: /dub [name|all] x y z
      
   fire:
      description: Remove an actor(s). Name can be "all".
      usage: /fire name
      
   action:
      description: playback actor or all actors
      usage: /action [actorname]
      
   actionrec:
      description: playback actor or all actors and record
      usage: /actionrec [actorname]
      
   loop:
      description: Set an actor (or "all") to loop
      usage: /loop [on|off] actorname

   visible:
      description: Set an actor visible to all other players or just the author.
      usage: /visible [on|off] actorname

   reset:
      description: Rewind actor or all actors
      usage: /reset [actorname]
      
   remove:
      description: Remove an actor
      usage: /remove [actorname]
      
   saveactor:
      description: Save an actor's recording to a file
      usage: /save actorname filename
      
   savescene:
      description: Save all actor recordings to dir/actorname
      usage: /savescene scenename
      
   loadactor:
      description: Spawn an actor with the give recording file
      usage: /load actorname filename
      
   loadscene:
      description: Load and spawn all actor recordings from dir
      usage: /loadscene scenename
      
